---
dist: xenial
language: python
python:
  - "3.6"
install:
  - pip install pipenv
  - pipenv install --dev
before_script:
  - psql -U postgres -c 'CREATE DATABASE "insights";'
  - psql -U postgres -c 'CREATE ROLE "insights" WITH LOGIN PASSWORD '\''insights'\'';'
  - psql -U postgres -c 'GRANT ALL PRIVILEGES ON DATABASE "insights" TO "insights";'
script:
  - ./test_api.py
  - ./test_unit.py
services:
  - postgresql